FreeCodeCamp/wiki

- Map.md
I ordered the section to match the current map, only a few waypoints
from the basic JS section are currently missing.
> Added missing sections

- bonfire-roman-numeral-converter.md
Fixes FreeCodeCamp/FreeCodeCamp/issues/3991
> fixes/Roman Numeral Converter Infinite Loop Issue

- js-Array-prototype-join.md
- js-Array-prototype-reverse.md
- js-String-prototype-slice.md
Added wiki pages:
js-Array-prototype-join.md
js-Array-prototype-reverse.md
js-String-prototype-slice.md
Closes issues: 
#3435, #3448, #3454
Please let me know if anything else is necessary or if you have a preferred format for wiki page PRs. This is my first PR for FCC.
> Added wiki pages. Closes Issues #3435 #3448 #3454

- Bonfire-Sum-All-Primes.md
Added recursive Solution to wiki
> Update to Bonfire-Sum-All-Primes.md

- List-of-Free-Code-Camp-city-based-Campsites.md
It appears that local group has been created already, so I removed mine duplicated one and ask to add https://www.facebook.com/groups/free.code.camp.kharkiv/
> Changed "Kha" to "Kharkiv"

- bonfire-mutations.md
A new solution to bonfire-mutations. Please review.
> A new solution to bonfire-mutations

- Bonfire-Pig-Latin.md
Added a solution using RegExpressions and Intersection of two expressions
> Added a new solution

- Array.isArray.md
- Math.max.md
- Math.min.md
- js-Array-prototype-concat.md
- js-Array-prototype-every.md
- js-Array-prototype-forEach.md
- js-Array-prototype-lastIndexOf.md
- js-Array-prototype-reduce.md
- js-Array-prototype-sort.md
- js-Array-prototype-splice.md
Closes FreeCodeCamp/FreeCodeCamp#3462, closes FreeCodeCamp/FreeCodeCamp#3461
closes FreeCodeCamp/FreeCodeCamp#3459, closes FreeCodeCamp/FreeCodeCamp#3458,
closes FreeCodeCamp/FreeCodeCamp#3453, closes FreeCodeCamp/FreeCodeCamp#3449,
closes FreeCodeCamp/FreeCodeCamp#3447, closes FreeCodeCamp/FreeCodeCamp#3445,
closes FreeCodeCamp/FreeCodeCamp#3443, closes FreeCodeCamp/FreeCodeCamp#3442.
> Add new articles

- Bonfire-DNA-Pairing.md
added a solution using direct array manipulation
> added a shorter solution

- Bonfire-Missing-letters.md
Added two shorter solutions and fixed some styling issues
> Added two shorter solutions for Bonfire missing letters and fixed some wiki formatting

- js-String-prototype-concat.md
- js-String-prototype-indexOf.md
Closes FreeCodeCamp/FreeCodeCamp#3430 
Closes FreeCodeCamp/FreeCodeCamp#3429 
Added 2 new pages for String.prototype.concat and String.prototype.indexOf
If these are okay, then I would like to add rest of the String prototypes in this branch itself.
> new pages for String.prototype.concat and String.prototype.indexOf

- Bonfire-Sorted-Union.md
Added a solution that uses filter to tackle duplicate elements
> Added my solution to bonfire sorted union wiki

- Object.getOwnPropertyNames.md
- Object.keys.md
- String.fromCharCode.md
- String.length.md
- js-String-prototype-charAt.md
- js-String-prototype-charCodeAt.md
- js-String-prototype-lastindexOf.md
- js-String-prototype-match.md
- js-String-prototype-replace.md
- js-String-prototype-substr.md
- js-String-prototype-substring.md
- parseInt.md
Closes freecodecamp/freecodecamp#3438, closes freecodecamp/freecodecamp#3437,
closes freecodecamp/freecodecamp#3434, closes freecodecamp/freecodecamp#3433,
closes freecodecamp/freecodecamp#3432, closes freecodecamp/freecodecamp#3431,
closes freecodecamp/freecodecamp#3428, closes freecodecamp/freecodecamp#3427,
closes freecodecamp/freecodecamp#3426, closes freecodecamp/freecodecamp#3425,
closes freecodecamp/freecodecamp#3424, closes freecodecamp/freecodecamp#3423.
> Add more new articles

- Bonfire-Chunky-Monkey.md
- bonfire-repeat-a-string-repeat-a-string.md
Issue #111 wasn't fixed properly.
> Fixed incorrect parameters & removed unnecessary semicolon

- Saturday-Summit-August-2015.md
- Saturday-Summit-November-2015.md
- Saturday-Summit-October-2015.md
- Site-Improvements-August-2015.md
- Site-Improvements-October-2015.md
I've fixed some funky file names - one was set to Quincy's e-mail address - and I've normalized the display:
Saturday Summit <Month> <Year>
Site Improvements <Month> <Year>
> Normalize Summit and Improvement Names

- Bonfire-Drop-it.md
- The removed solution was wrong as it used `filter()` and removed all the elements that didn't satisfy the condition rather than just the ones that don't satisfy the condition before the index of the first found element
- Added my solution to the problem 
- fixed formatting
> Added my solution and removed an incorrect solution for bonfire drop it

- Bonfire-Steamroller.md
Added a solution using reduce and recursion to flatten all nested array elements
> Added my solution to bonfire Steamroller

- Bonfire-Binary-Agents.md
Added a shorter solution that uses `split()`, `map()` and Spread Operator to provide a cleaner solution
> Added my solution to Binary Agents Bonfire

- Gitter-Moderation-Policy.md
> Add link to code of conduct

- Bonfire-Repeat-a-String-Repeat-a-String.md
I added another solution for this bonfire which uses a new repeat function from ES6.
> added solution to bonfire article Repeat a String

- How-To-Create-A-Pull-Request-for-Free-Code-Camp.md
- How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp.md
Two articles on how to create and maintain a local fork and how to submit a PR to FCC.
Request Review by @ltegman and @bugron for completeness.
> How to Fork and Create Pull Requests

- How-To-Create-A-Pull-Request-for-Free-Code-Camp.md
- How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp.md
Some markdown and formatting fixes.  Added more explicit text about using the `staging` branch at a user's request..
> Markdown fixes and minor edits to PR docs.

- code-formatting.md
Remove backticks image as it duplicates the preceding text.
> Remove Backticks Image

- Disable-Code-Auto-Run.md
- Loop-Protect.md
Two new articles on new FCC Features:
* Loop Protect
* Disable Code Auto-Run
Hold release until Code Auto-Run has been merged: FreeCodeCamp/FreeCodeCamp#5001
> Add Loop Protect and Disable Code Auto-Run Articles

- Bonfire-Sum-All-Numbers-in-a-Range.md
Here we go again, I edited the file and added more details to the explanation since people were asking me about the arrow function and such. It has links and a brief explanation.
> Added extra explanation and links to second solution

- Bonfire-Exact-Change.md
Tested on live site 12/6/2015
Closes #143
> Update Exact Change Solution with a passing solution

- 10-Steps-To-Plan-Better-So-You-Can-Write-Less-Code.md
- 5-Steps-to-organizing-a-successful-Campsite-event.md
- Getting-a-coding-job.md
- Home.md
I'm trying to work on my technical writing skills and my portfolio, so I did some proofreading changes just to get used to working with GitHub.
This whole project looks fantastic, by the way! If I had more time I'd totally sign up!
Thanks!
> Proofreading Changes

- Bonfire-Style-Guide.md
-removed repeated word 'the the' 
-checked document for other obvious grammar and spelling issues.
> fixed grammar issue and proof-read

- Bonfire-Binary-Agents.md
The "Hint: 1" header was missing
> updated binary agents (markdown)

- JS-Resources.md
As recommended by @terakilobyte
> Add Javascript Allonge Six Book

- Bonfire-Validate-US-Telephone-Numbers.md
The second solution in the file didn't pass the new tests
> Removed outdated solution

- code-formatting.md
Preview: https://github.com/abhisekp/wiki/blob/fix/code-format/code-formatting.md
> Add coding language instruction

- Bonfire-Slasher-Flick.md
Hi this is my second ever PR, so thank you for your patience with me! I've made three changes to this wiki page.
1. It seems that this bonfire doesn't involve the use of factorials, so I removed the comment in the problem explanation. 
2. I've replaced the broken image with a working image from Bonfire-Mutuations.md.
3. I added codeblock highlighting, made minor grammar fixes where necessary, and changed the title formatting to be more consistent with other bonfires.
> fix: remove unnecessary factorial comment, fix broken img link, and minor grammar fixes

- List-of-Free-Code-Camp-city-based-Campsites.md
List of missing cities + Additional cleanup.
> Add missing cities (Dec 2015)

- Bonfire-Pig-Latin.md
in my solution I have created a separate function that checks if the letter is consonant. By that I am dividing the problem into smaller problems. This approach is useful in designing big applications where it is important to create reusable functions.
> added the third solution for pig latin

- Waypoint-Change-the-Font-Size-of-an-Element.md
- Waypoint-Set-the-Font-Family-of-an-Element.md
- Waypoint-Style-Multiple-Elements-with-a-CSS-Class.md
- Waypoint-Uncomment-HTML.md
Clarifications on waypoints:
Uncomment: cleared up the Javascript confusion. This is a HTML comment
waypoint.
Style: added clarification
Font-family: the previous wiki was showing the exact same text as a
different waypoint for importing a google font. Completely overhauled to
reflect the built-in font-family waypoint
Font-size: added what px means and link to other units
> Waypoints wiki updates

- Bonfire-Symmetric-Difference.md
The filterFunction only adds unique items. Filtering again is unnecessary.
> Remove redundant code

- Waypoint-Import-a-Google-Font.md
- Waypoint-Inherit-Styles-from-the-Body-Element.md
- Waypoint-Override-Class-Declarations-by-Styling-ID-Attributes.md
More typo fixes and clarifications in the HTML waypoints
> HTML Waypoints

- Bonfire-Mutations.md
I'm sure the explanation can be written more clearly but eloquence isn't my forte either. 
Help, anyone?
> Add declarative solution

- Bonfire-Factorialize-a-Number.md
> Clean-up crew

- Bonfire-Sum-All-Odd-Fibonacci-Numbers.md
have broken down the problem into two parts. First created the array of fibonacci numbers then found the sum of odd numbers
> added second solution to Sum All Odd Fibonacci Numbers

- List-of-Free-Code-Camp-city-based-Campsites.md
Keeping the list updated as they come shall be easier than massive catching ups
> Add Panama city, FL

- Bonfire-Reverse-a-String.md
As we just received some BP @ gitter, I realised it would be nice to know what they're thanking for.
> Add reference to specific bonfire when sending thanks

- Waypoint-Storing-Values-with-the-Equal-Operator.md
Initial wiki page with waypoint explanation.
> Created entry for storing with equal operator

- Map.md
This is an initial commit, it only has the placeholders on the right
place and also updated some old ones and removed deprecated content. I
still need to create the pages and give proper links.
> Update Map to reflect new Waypoints and Ziplines

- Free-Code-Camp-completion-language-requirements.md
Add Duolingo as an additional english resource.
> Add additional language resource

- Bonfire-Everything-be-True.md
Small stylistic changes to make page more readable. Also removed function calls as they are irrelevant to solutions code.
> stylistic update

- List-of-Free-Code-Camp-city-based-Campsites.md
> Update Cities, Early January 2016 

- Waypoint-Appending-Variables-to-Strings.md
- Waypoint-Concatenating-Strings-with-Plus-Operator.md
- Waypoint-Concatenating-Strings-with-the-Plus-Equals-Operator.md
- Waypoint-Constructing-Strings-with-Variables.md
- Waypoint-Escape-Sequences-in-Strings.md
- Waypoint-Escaping-Literal-Quotes-in-Strings.md
- Waypoint-Find-the-Length-of-a-String.md
- Waypoint-Quoting-Strings-with-Single-Quotes.md
For the `Basic JavaScript` topic
> Created Basic JavaScript waypoints 24 to 31

- Start-Here.md
- What-you-will-learn,-and-in-what-sequence-you-will-learn-it.md
> Updated reference pages

- List-of-Free-Code-Camp-city-based-Campsites.md
> Update cities January 5 2016

- How-to-create-a-Campsite-for-your-city.md
- List-of-Free-Code-Camp-city-based-Campsites.md
Removed list of cities as the were already added in #238
> update contact info for new campsites to mine (instead of quincy).

- Checkpoint-Shopping-List.md
- Checkpoint-Word-Blanks.md
Created Shopping List and Word Blanks
> Created 2 new checkpoints pages

- Map.md
- Waypoint-Understand-String-Immutability.md
> Added missing links to map

- Bonfire-Inventory-Update.md
- Bonfire-Map-the-Debris.md
- Bonfire-Spinal-Tap-Case.md
Solution added to bonfires:
Bonfire-Inventory-Update, Bonfire-Map-the-Debris and Bonfire-Spinal-Tap-Case.
> Solution added to bonfires

- Bonfire-Caesars-Cipher.md
> Added wiki for Bonfire: Caesar's Cipher

- Checkpoint-Golf-Code.md
Created Checkpoint-Golf-Code help article
> Created Checkpoint Golf Code

- Checkpoint-Counting-Cards.md
Version 1 of Checkpoint - Counting Cards
> Created Checkpoint - Counting Cards

- Bonfire-Missing-letters.md
Wanted to synthesise the solutions, but I'm not sure if the different examples actually do give insights on methodically different albeit apparently similar ways.
What do you think, @Rafase282? Help me come up with a `.reduce` version so we don't have to use additional variables, initialise it with the starting char code and return directly? anyone?
----
Assigned to self to remind me I want to figure this one out :+1:
> Cleaning crew, Add declarative solution.

- Checkpoint-Record-Collection.md
> Created Checkpoint: Record Collection

- Map.md
All are working but Record Collection. Maybe it has yet to be pushed
live?
> Updated map links

- List-of-Free-Code-Camp-city-based-Campsites.md
> Add cities, Jan 11 2016

- Checkpoint-Profile-Lookup.md
Created wiki entry for this checkpoint
> Checkpoint - Profile Lookup

- How-To-Contribute-To-The-Wiki.md
> Fixed a typo

- Test-Me.md
- testingjson.md
> Deleting empty files

- List-of-Free-Code-Camp-city-based-Campsites.md
> Add cities, jan 14

- How-GitHub-Issue-Moderators-AKA-Issue-Mods-Work.md
Massive rewrite of the Issue Mod guide.
I've tried to be exhaustive, but have no doubt missed key topics.  Would love feedback/corrections/additions.
tag: @FreeCodeCamp/issue-moderators
> Update Issue Moderation Guide

- Bonfire-Repeat-a-String-Repeat-a-String.md
The added solution is a compact version, similar to solution 3, that
uses the same logic, but uses the compact version of the if statement to
reduce the size of the function.
> Added compact solution for the challenge.

- accessibility-101.md
This is the first out of three articles I promised to write on the Curriculum development gitter channel.
This one deals with the very basics, more to come. I didn't really find a suitable branch to request to except for master . If this is the wrong branch, please advise on where you would rather see it merged.
> Accessibility 101: first article of three

- Help-Rooms.md
Update the list to point to the more current rooms.  Use a more compact format.
> Update Quick Help Rooms List

- List-of-Free-Code-Camp-city-based-Campsites.md
Still adding cities for today, will edit, squash and remove "in progress" when ready to merge :100:
> Campsite additions

- List-of-Free-Code-Camp-city-based-Campsites.md
- World-Language-Chat-Rooms.md
Also, cleanup for language specific chatrooms
> add cities, Jan 25-27 2016

- Bonfire-Caesars-Cipher.md
I'm not sure about my english skills. Explanations section may need a lookup :)
> Bonfire-Caesars-Cipher --- New solution with map() method

- What-to-do-if-you-speak-a-language-that-Free-Code-Camp-does-not-yet-support.md
> Updating how to contribute to translation

- Bonfire-Friendly-Date-Ranges.md
Added extra conditions to pass the remaining two cases.
> Updated solutions for "Friendly Date Ranges" fixes #296

- List-of-Free-Code-Camp-city-based-Campsites.md
> Add cities, Jan 31 2016

- List-of-Free-Code-Camp-city-based-Campsites.md
> Add cities, Feb 1 2016

- js-closures.md
As stated on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures . Previous code was in lexical format. new code shows closure of previous code
> changed js-closures.md to show a closure

- js-for-of-loop.md
* Changed or to of
* fixed Capitalization 
* added Arguments  object example
* Added link to argumanets[@@iterator]
> fixed typo (or to of) formatting and added arguments object example

- js-for-loop.md
* Added syntax and explanations for parts of for loop.
* Added common pitfalls section
> Changed js-for-loop

- js-Array-prototype-filter.md
Updated description and added callback parameters
> Elaborated on filter() and callback parameters

- Algorithm-Smallest-Common-Multiple.md
Closes FreeCodeCamp/FreeCodeCamp#3410.
- Lints fenced code blocks
- Adds to beginning explanation section
- Add backticks to indicate code when appropriate
- Made text width 80 characters
Any feedback is welcome. I wasn't really sure what was expected for "rewrite and simplify explanation" of the challenge.
> Rewrite and add to Smallest Common Multiple

- How-to-start-when-you-are-stuck-(II).md
1 letter typo fixed in the 2nd sentence "Well it wants us.."
Changed as to us.
> fixed typo, changed as to us

- Updates-February-11-2015.md
Also, where's the calculator challenge? :(
> Small typo

- Algorithm-Chunky-Monkey.md
>`Uncaught ReferenceError: newArray is not defined`
Fixed
Added an example avoiding size counting
> Fixed Solution 3. Added Solution 4

- Debugging-JavaScript-with-Browser-DevTools.md
This guide will provide users with tips to:
- Know basics of DevTools.
- Some common shortcuts and features.
- Using Source maps for Scripts.
Note : I have covered only Google Chrome DevTools, should I mention something about other browsers as well, mostly the steps are same for almost all modern browsers.
> Add guide to Debugging using browser DevTools

- Algorithm-Title-Case-a-Sentence.md
- Move code explanation underneath its solution
- Remove minimal solution
- Add Minimalist solution using regex and its code explanation
> Add solution to Title Case

- Gitter-Moderation-Policy.md
- Link to the official website page of Code of Conduct.
- Pretty markdown format for the link title.
> Update markdown format and link

- Algorithm-Title-Case-a-Sentence.md
It's added as a Fourth solution to the problem in `Algorithm-Title-Case-a-Sentence.md` file.
> Title-case-a-sentence algorithm solution using Array.prototype.map()

- Algorithm-Falsy-Bouncer.md
If my description is unclear or warrants explaining in more detail please feel free to add to it.
> Adds second solution and explanation for 'Falsy Bouncer' algorithm

- Algorithm-Symmetric-Difference.md
Solution 1 improved to pass all the test cases.
Verified that solution 2 still works.
> fixes #370 : Solution 1 improved to pass all the cases.

- Git-Checkout-A-Remote-Branch.md
- Git-Delete-a-Branch-both-locally-and-remotely.md
- Git-Force-Git-to-overwrite-local-files-on-pull.md
- Git-Undo-Redo-A-Commit.md
Topics covered:
This PR addresses the topics mentioned above. I have added attributions to the original answers in some articles because of their conceptual nature of the workflow, and left out attributions in the standard articles like `Checkout Remote Branch`
Will Squash the commits once QA'ed.
> Adding New Content for the Wiki

- Currying.md
> Currying Article

- Algorithm-Convert-HTML-Entities.md
Added previous solutions, merged two of them and renamed them by levels. Also added original credits back.
> Added previous Solutions

- Algorithm-Convert-HTML-Entities.md
> Fixed typo

- medium-example-wiki-article.md
This covers the content needed for the wiki article
> Create an example wiki article

- Get started with Node.js.md
Curriculum Specific
Get started with Node.js
> Create wiki article about Get started with Node.js

- Get started with Node.js.md
Now it has links without the repeated name, I think it looks better that way, also fixed some minor indentation issues. There  are more links from here that could be added so it would be nice to know about the criteria @ianseabrook used on PR #396
> Updated recently merged article

- Installing WordPress locally on Mac.
I just made things easier to spot, and added some links for downloading files but overall is the same thing.
> Edited Article about Installing WP on a MAC

- Algorithm-Symmetric-Difference.md
- updated explanation of code.
- changed == in unique to ===.
> In-depth explanation of code

- react-webpack-es6-starter.md
> added react-webpack-es6-starter.md

- Home.md
This should make it easier for contributors to get started.
> Added links and more details

- equality-vs-identity.md
Created article comparing equality and identity operators in JavaScript.
> Create wiki article about == vs === operator

- using-anonymous-self-executing-functions-for-private-namespacing-in-your-js-apps.md
Create a wiki article for using private namespaces in JS apps using anonymous self-executing functions
> Create wiki article for using private namespaces

- Home.md
Made changes proposed by @QuincyLarson
> Updated about signatures

- Page-redirects-using-javascript.md
Create wiki article for page redirects using JavaScript, explain how to use them and a fallback to use if a user has JS disabled.
> Create wiki article for page redirects

- WebDevelopment in Python : A Brief Overview.md
This adds the first wiki article on an alternative platform to develop web-application back-ends, namely Python.
> Create first wiki article for Python Web Dev

- Reduce-made-easy.md
I am adding an article on how to use Array.prototype.reduce() in day-to-day problems; and get comfortable with it.
> Add Wiki on How to Be Comfortable Using Reduce With simple examples

- Algorithm-Title-Case-a-Sentence.md
Add proper heading markdown format for code solutions.
> Update markdown formatting for Title Case

- Git-Change-the-URL-of-a-remote-repository.md
This PR adds a new wiki article w.r.t #367 : Git-Change-the-URL-of-a-remote-repository.md
Lemme know if any changes needed in the content. 
Thanks.
> Added a new wiki article - Change the URL of a remote repository

- gulp-basics.md
Removed signature.
Fixed markdown issues and typos
Closes #445
> Added gulp-basics to wiki.

- writing-a-markdown-file-using-atom.md
Some changes
Closes #447
Don't merge yet
> added markdown file

- Check-if-element-is-hidden-js-or-jquery.md
Make sure your contribution addresses the points mentioned below:
**Filenames:**
- Your filename should NOT contain any special characters or spaces.
- Use only "-" to separate words in the filename.
- Filenames should have the ".md" extension.
**Formatting:**
- Ensure that you use markdown syntax for articles.
- Checkout the guides for reference:
1. [Master Markdown](https://guides.github.com/features/mastering-markdown/)
2. [Working with Advanced Formatting](https://help.github.com/articles/working-with-advanced-formatting/)
**Commits and Squashing:**
- Your Pull Request/Submission should have only one commit.
- For multiple commits follow the [guide to squash them](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one)
- If you are new to …
> Create wiki article for checking hidden elements

- .github/PULL_REQUEST_TEMPLATE.md
I think this would make it clear. We still get pull request using html and css.
> Further edits.

- Install-Django-Flask.md
Creating a wiki article entry, for the installation and set-up process of Django and Flask framework.
> Create Installation Guide for Django and Flask

- Git-Push-Local-To-Remote-Repository.md
This PR adds a new wiki article w.r.t #367 : Git-Push-a-new-local-branch-to-a-remote-repository.md
Lemme know if any changes needed in the content.
Thanks.
> Added a new wiki article -  Push a new local branch to a remote Git repository

- js-Scopes.md
- js-scope.md
The previous article barely had any description and wasn't very helpful.
This is a more in-depth exploration of scopes, and there's a good chance that it's super confusing as well, so let me know if I'm not being clear enough.
Also, I changed the file name from `js-scopes.md` to `js-Scopes.ms` because that seemed to be the convention that the other files were following, though I am not sure if that's correct.
#367
> Rewrite article on JS scopes

- Official-Free-Code-Camp-Chat-Rooms.md
Updating the list of chatrooms to include new back-end languages.
> Update chatroom lists with new back-end languages

- Official-Free-Code-Camp-Chat-Rooms.md
I forgot to add the .NET chatroom in the list of chatrooms when I updated earlier.
@Rafase282 @SaintPeter @hallaathrad @raisedadead please review.
> Add .NET chatroom in chatroom list

- Reduce-made-easy.md
Updated typo and linkified method calls for Array Reduce Wiki
> Update typo and linkify method calls for Array Reduce

- dotnet.md
- elixir.md
- go.md
- java.md
- php.md
- python.md
- ruby.md
I am adding an individual file for each of the back-end languages we would be supporting.
> Add back end language stubs

- es.lang/Politica-De-Honestidad-Academica.md
Translates to Spanish the article: Academic-Honesty-Policy.md into the
file: Política-de-honestidad-académica.md
Rename Política-de-honestidad-académica.md to Politica-De-Honestidad-Academica.md
Closes #477
> Add a Spanish translation from English article

- Capitalize-First-Letter-Of-String.md
Created New Content for the Wiki (issue #367)
Capitalize the first letter of string in JavaScript
Created New Content for the Wiki (issue #367)
Update Capitalize-First-Letter-Of-String.md
Modified the last step with string.prototype
minor edits
Closes #482
> Capitalize the first letter of string in JavaScript

- .github/PULL_REQUEST_TEMPLATE.md
It should be more visible now.
> Update template to make filename structure clear

- Python-Basics.md
- Python-Introduction.md
This is the starting of wiki entries for Python. Python challenges would be based on this.
> Add python intro and basics

- JS-Comparison-Operators.md
closes #362 
Lemme know if any changes needed.
> Comparison Operators

- .github/PULL_REQUEST_TEMPLATE.md
Minor style changes and typos.
> Text proofing

- es.lang/Politica-De-Honestidad-Academica.md
[Here](https://docs.google.com/spreadsheets/d/1c60Sl4MAAsZ7biCPgur7A4aVqhErIfwrE1SulPqbOGo/edit#gid=0) is the guidelines for Spanish translation.
> Updated translation

- Install-Django-Flask.md
- Python-Basics.md
- Python-Functions.md
- Python-Introduction.md
- Python-More-Builtin-Types.md
- Python-Operators.md
- Python.md
- Web-Development-in-Python.md
> Fix and update links in Python articles

- Python-Basics.md
Testing Reference Linking by replacing 3 instances of absolute Linking in Python-Basics.md
> Test Reference Linking

- JS-Strict-Mode.md
New wiki content w.r.t #367 
Please review and lemme know if any changes needed. 
Thank you.
> JS Strict Mode

- Git-Amend-Last.md
> Created git amend document.

- Ruby.md
Improves the ruby description to beginners, fixes a spelling mistake and also made this more elaborative and informative.
> improving ruby description and introduction

- JS-Get-Timestamp.md
Adds new wiki file w.r.t #367. Please review.
> Adds JS-Get-Timestamp.md

- Setting-Up-A-React-ES6-Webpack-Project.md
Fix webpack and webpack-dev-server installation command
> Fix webpack and webpack-dev-server installation command

- Linux.md
I've created first version of Linux introduction.
Looking for feedback! 
@alayek @koustuvsinha  @raisedadead @Rafase282
> create linux introduction

- Python.md
Add Python Resources link to python home
> Add Python Resources link to python home

- js-Global-Object.md
I believe this closes #358, but as I commented on the issue, it is unclear whether the issue is for the global object or the Object constructor.
> Add article on the global object

- Algorithm-Drop-it.md
Reverts FreeCodeCamp/wiki#513
Code will be changed a bit.
> Revert "added a small fix to drop-it algorithm, solution was creating an infi…"

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
Added link to both templates so users can learn to write better commit
messages.
> Add guide to proper git commit messages to PR and Contributing templates

- Help-Rooms.md
Added the .Net help chat room to CamperBot's help room list so users can
find it easily.
> Add .Net help chat room to CamperBot room list

- Java-Introduction.md
Starting to add Java Wiki files. :smile: 
Please review @alayek , @Rafase282 !
> Add Java Introduction

- JS-Current-URL.md
> Current URL in JavaScript

- Git-Resources.md
Updating Git Resources with list of Git Articles.
> Update Git Resources list

- What-to-do-if-you-speak-a-language-that-Free-Code-Camp-does-not-yet-support.md
Converted the link to markdown.
> Update link on recommendations.

- Django-Start-Project.md
Add Guide for starting a Django project. 
@alayek I didn't include a link to the previous/next article. Will have to add them once we know the plan and whats next. If you want me to continue on I can. And I will add the link to the previous article once it's created.
> Add Django-Start-Project.md

- Map.md
> Update map and add placeholders

- .github/CONTRIBUTING.md
Updated the links, were leading to 404s.
> Fix links in CONTRIBUTING guidelines

- Java-Resources.md
Add Java Resources as per #534 
@Rafase282 @alayek please review!
> Add Java Resources

- Python-Resources.md
I couldn't test this locally. I guess we can test it only if it's live.
@Rafase282 @koustuvsinha FYI.
> Update Python Resources with fragmented URLs

- Algorithm-Exact-Change.md
Changes made because of my changes in FreeCodeCamp/FreeCodeCamp#7299.
- Reflow Wiki text width to 80 characters
- Update Hint 2 for better readability
- Change solution function name to match main repo
- Lint solution, remove extra spaces, change from four spaces to two spaces
> Update Exact Change solution function name + lint

- Browser-Storage.md
This article is aimed at explaining how to store in localStorage and sessionStorage.
> Proposing a new Wiki article about browser storage

- Known-Issues-With-Codepen.md
I spent about a week trying to debug a problem that ended up being an issue with a Chrome extension conflicting with Codepen. This file is meant to provide a list of known issues with Codepen, to reduce frustration in the future.
Rename known-issues-with-codepen to known-issues-with-codepen.md
I added ".md" to the file name. Hopefully this resolved the issue.
Update known-issues-with-codepen.md
Update known-issues-with-codepen.md
Update and rename known-issues-with-codepen.md to known-issue-with-codepen.md
Update known-issue-with-codepen.md
Renamed filename
closes #498
> Known Issues With Codepen

- Challenge-Solution-Template.md
- Checkpoint-Convert-Celsius-to-Fahrenheit.md
- Checkpoint-Counting-Cards.md
- Checkpoint-Golf-Code.md
- Checkpoint-Profile-Lookup.md
- Checkpoint-Record-Collection.md
- Checkpoint-Shopping-List.md
- Checkpoint-Stand-In-Line.md
- Checkpoint-Word-Blanks.md
Removed the hard links and made them into relative ones. Also Create a file to auto end of line normalization.
> Change hard links to relative ones

- Permutations.md
> Add Permutations Article.

- Known-Issues-With-Codepen.md
> Updates format

- Programming-Methodology.md
Adds the article that was deleted on #584 back with a better name and
without the unrelated material
> Adds article back

- List-of-Free-Code-Camp-city-based-Campsites.md
> Add cities, Mar 19 2016

- Algorithm-No-Repeats-Please.md
Added code to immediately return 0 if str contains same letter. Performance improvement for case like str = "zzzzzzzz"
> Return 0 if str contained same letter

- Algorithm-Inventory-Update.md
Update the wiki article corresponding to the main repo and it's updates to unique function names.
Fixes:
`inventory()` to `updateInventory()`
References #615
> Updated algorithm challenge Update Inventory

- Algorithm-Return-Largest-Numbers-in-Arrays.md
> Uses internal links

- How-To-Contribute-To-The-Wiki.md
@raisedadead @Rafase282 please do a review and let me know if you want me to add these instructions in more places.
The PR comment template already has the line at 3rd from the top that filename has to end in .md.
> Clearly state that new files in wiki has to have .md extension

- PHP-Variables.md
Wiki article for PHP Variables.
> Article-for-PHP-Variables.md

- Algorithm-Roman-Numeral-Converter.md
Updated Algorithm-Roman-Numeral-Converter.md hints #1 & #2 for clarity.  Also fixed a little formatting.
> Updated Algorithm-Roman-Numeral-Converter.md hints #1 & #2 for clarity

- C-Sharp.md
- DotNet-Platform.md
First draft for introduction of .Net platform and place holder for c-sharp.
> Template for .net platform and placeholder for c-sharp

- Algorithm-Chunky-Monkey.md
- Algorithm-Confirm-the-Ending.md
- Algorithm-Friendly-Date-Ranges.md
- Algorithm-Repeat-a-String-Repeat-a-String.md
- Algorithm-Truncate-a-String.md
- Algorithm-Where-do-I-belong.md
Updated function names in wiki articles to match the main repository.
Addresses wiki [issue 615](https://github.com/FreeCodeCamp/wiki/issues/615).
Changes made to:
Algorithm-Friendly-Date-Ranges.md
Algorithm-Confirm-the-Ending.md
Algorithm-Repeat-a-String-Repeat-a-String.md
Algorithm-Truncate-a-String.md
Algorithm-Chunky-Monkey.md
Algorithm-Where-do-I-belong.md
> Changed function names to match main

- code-editors-wiki-article.md
Simple article on code editing software, with a summary of a few popular editors available for download.
> Create wiki article about code editors

- Integrated-Development-Environments.md
- Online-VS-Offline-IDE.md
> Recreates article and definition

- Installing-Necessary-CLI-Tools.md
This article will explain to readers how to install widely used CLI tools for web development.
> Create a wiki article on installing CLI tools

- fr.lang/Challenge-Informer-avec-l-Element-de-Paragraphe.md
French Translation -> Challenge-Inform-with-the-Paragraph-Element.md
> Translation Article: Challenge Informer avec l Element de Paragraphe

- fr.lang/Challenge-Titre-avec-un-Element-h2.md
French Translation - > Challenge-Headline-with-the-h2-Element.md
> Translation Article: Challenge Titre avec un Element h2

- fr.lang/Create Challenge-Dire-Bonjour-Aux-Elements-HTML.md
French Translation -> Challenge-Say-Hello-to-HTML-Elements.md
> Translation Article: Challenge Dire Bonjour Aux Elements HTML

- Vagrant-Up.md
This runbook should work to get Vagrant up and running so that you can run PHP on your local machine. I will clean up the runbook, make it easier to read, as well as taking out a part that might not be necessary for Vagrant to run.
> Article: About Vagrant-Up

- HTML-Entities.md
> Add article on HTML Entities

- Become-A-Wiki-Mod.md
- Wiki.md
Feel free to pick a section and write it up. A big part of it is already
written and just need to be linked or moved here.
> Placeholder for massive article

- NPM-Behind-Proxy.md
Similar to https://github.com/FreeCodeCamp/wiki/pull/690, except for `npm`.
> Add NPM Behind Proxy Article

- kr.lang/Home.md
> Translate Home.md into Korean

- Algorithm-Arguments-Optional.md
- Algorithm-Boo-who.md
- Algorithm-Convert-HTML-Entities.md
- Algorithm-DNA-Pairing.md
- Algorithm-Diff-Two-Arrays.md
- Algorithm-Drop-It.md
- Algorithm-Everything-be-True.md
- Algorithm-Finders-Keepers.md
- Algorithm-Pig-Latin.md
- Algorithm-Roman-Numeral-Converter.md
- Algorithm-Sorted-Union.md
- Algorithm-Where-art-thou.md
- Challenge-Comparison-With-The-Equality-Operator.md
- Challenge-Global-Vs-Local-Scope-In-Functions.md
- Challenge-Local-Scope-And-Functions.md
- Challenge-Passing-Values-To-Functions-With-Arguments.md
- Challenge-Use-Conditional-Logic-with-If-Else-Statements.md
- Checkpoint-Convert-Celsius-to-Fahrenheit.md
- Checkpoint-Profile-Lookup.md
- Checkpoint-Record-Collection.md
- Checkpoint-Stand-In-Line.md
Addresses [issue 615](https://github.com/FreeCodeCamp/wiki/issues/615) to match function names in wiki articles to the corresponding challenge. 
This PR is related to [freecodecamp issue 7899](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7899) and [freecodecamp issue 7688](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7688) where the original function names were edited.
Some of the articles are too small or do not include function names and were not changed.
> Match function names in wiki articles to match challenges

- List-of-Free-Code-Camp-city-based-Campsites.md
> Fix image not rendering on Gatsby and invalid Markdown

- Help-Rooms.md
- Categorize Help Rooms List
- Reformat Markdown
- Help Rooms ordered based on purpose
- Other Rooms ordered alphabetically
> @camperbot compatible
> Reformat Help Room Markdown

- Creating-Twitch-Account.md
> Article: Setting Up Twitch

- Stream-Your-Coding-Sessions-on-Twitch.tv.md
- Twitch.md
I updated this page to the newest requirements of how we let users stream. Leave any suggestions below!
> Article: How to Stream Live Coding on FreeCodeCamp

- Brownie-Points.md
Fixes Markdown Notation of List for Consistency.
see discussion in: https://github.com/FreeCodeCamp/wiki/pull/714
> Fix Markdown Notation of Ordered List

- Java.md
I thought it would be interesting knowing a few more things about Java's platform independence.
I also added the use case of using JAVA in backend development.
> Added information about JAVA

- fr.lang/Challenge-Décommenter-HTML.md
French Translation: Challenge-Uncomment-HTML.md
> French Translation: Challenge Uncomment HTML

- Creating-Twitch-Account.md
- Stream-Your-Coding-Sessions-on-Twitch.tv.md
- Twitch.md
> Updating Twitch Articles regarding YouTube switchover

- Algorithm-Smallest-Common-Multiple.md
I just simplified the swap that is being made in the while loops of the last two example solutions. I think this way it's clearer.
> Change while loops in last two solutions to use only 3 assignments

- Wiki-Labels-Guide.md
<h1 align="center">Add Wiki Labels Guide</h1>
Added complete details about Wiki Labels and their usage for use by Wiki Maintainers and Contributors.
@FreeCodeCamp/wiki-mods If you've any suggestions, please feel free to comment.
Thanks @Rafase282 for explaining about everything in a sweet :yum: and easy to understand manner and thanks @theflametrooper for joining the team and encouraging me to write this one :smiley: 
----
Yep! This is @camperbot compatible. :alien: 
----
Labels help in categorizing [**issues**](https://github.com/FreeCodeCamp/wiki/issues) and [**pull requests**](https://github.com/FreeCodeCamp/wiki/pulls). Use **_issue_ only** labels for issues and **_PR_ only** labels for pull requests. Listed here are labels for [**FreeCodeCamp …
> Add Wiki Labels Guide

- Clear-Your-Browser's-Local-Storage.md
A small modification on https://github.com/FreeCodeCamp/wiki/issues/748
> Add inline backticks for localstorage clear

- Algorithm-Caesars-Cipher.md
This is a fix to the issues raised in https://github.com/FreeCodeCamp/wiki/pull/677
I have moved and updated the solutions as @abhisekp has mention [here](https://github.com/FreeCodeCamp/wiki/pull/677#issuecomment-205645189).
I have also added functional solution by @abhisekp in the advanced section.
I have not included any constants to replace the magic numbers, because that would be overkill!
> Fix algorithm caesars cipher

- Wiki-Labels-Guide.md
This fixes bot response in gitter by lessening the number of characters i.e. 
gitter message character limit: `4096` :x: 
bot response characters: `2762` :white_check_mark: 
----
> **NOTE:** The link to [**Maintainer's Guide**]() and [**Review Board**]() are coming soon. 
----
> **Things to Check**
- Check all the links
- Check if the labels images load properly
- Check if the tooltip on hover over labels images show correctly
- See if the sentences are grammatically correct.
----
Yep! This is now 100% @camperbot compatible. :alien: 
----
Labels help in categorizing [**issues**](https://github.com/FreeCodeCamp/wiki/issues) and [**pull requests**](https://github.com/FreeCodeCamp/wiki/pulls). Use **_issue_ only** labels for issues and **_PR_ only** labels for pull requests. Listed here are …
> Fix Wiki Labels for gitter chat

- Translations-Guide.md
Adding on [request here](https://gitter.im/FreeCodeCamp/Translators?at=5719179ab129b59c56da4f9b)
> Add Bahasa Indonesia

- scripts/.eslintrc
- scripts/.eslintrc.js
- scripts/convert_files.js
- scripts/create_structure.js
- scripts/package.json
> Adds eslint and lint according to FCC config

- Campsites.md
- List-of-Free-Code-Camp-city-based-Campsites.md
Just so that people stop looking for their campsites in the map before looking at the list (because who cares for "find", right?)
> Add today's cities, link to assets repo and improve the map's description

- JS-while-Loop.md
Makes changed requested on #774  so closes #774
> Article: while Loop PR Update

- Java-Basics.md
- Java-Inheritance.md
- Java-Loops.md
* Added [REPL.it](https://repl.it) snippets wherever applicable
* Fixed code samples
@alayek have a look.
> Add REPL.it snippets to Java articles

- Git-Undo-Redo-A-Commit.md
- Undo-Git-Add.md
Article to undo ```git add``` before committing.
> Undo git add article

- Swashbuckle-Swagger-Operation-Alphabetical-Order.md
Improvements requested on #692
> Swashbuckle article improvements

- Bootstrap.md
> Article: Bootstrap

- Materialize.md
> Article: Materialize

- Python-Web-Applications.md
- Python-Web-Frameworks-Usage.md
- Python-Web-Frameworks.md
- Web-Development-in-Python.md
Splits the article, this one didn't have missing sections or To-Dos.
> Split Article Web Development in Python

- Project-Tribute-Page.md
Found some mistakes and corrected them. Simple punctuation
> FIXES SOME PUNCTUATION MISTAKES

- Wiki.md
Updates the title for the page and gives a better description.
> Wiki Central: New Title

- Python-Boolean-Operations.md
- Python-Interactive-Mode.md
- Python-Operation-Parenthesis.md
- Python-Operations-Comparisons.md
- Python-Operations-Numeric.md
- Python-Operators.md
- Python-Truth-Value-Testing.md
Splits article and adds some extra info.
> Split Article: Python Operators & Operations

- Algorithm-Caesars-Cipher.md
- Algorithm-Check-for-Palindromes.md
- Algorithm-Chunky-Monkey.md
- Algorithm-Confirm-the-Ending.md
- Algorithm-Factorialize-a-Number.md
- Algorithm-Falsy-Bouncer.md
- Algorithm-Find-The-Longest-Word-in-a-String.md
- Algorithm-Mutations.md
- Algorithm-Repeat-a-String-Repeat-a-String.md
- Algorithm-Return-Largest-Numbers-in-Arrays.md
- Algorithm-Reverse-a-String.md
- Algorithm-Seek-and-Destroy.md
- Algorithm-Slasher-Flick.md
- Algorithm-Title-Case-a-Sentence.md
- Algorithm-Truncate-a-String.md
- Algorithm-Where-do-I-belong.md
> Added repl.it snippets to all basic algorithms

- Pull-Request-Contribute.md
No issue reference. Just noticed a lack of spacing in this article randomly and thought I'd make a fix for it 😄  (not sure what happened to the last line of this change though...)
> Fix spacing of "PR" in PR Contribute article

- Setting-Up-Ubuntu-For-Programming.md
Feedback wanted from @Rafase282, @abhisekp and the [Linux](https://gitter.im/FreeCodeCamp/linux) chat room.
closes #785
> Article: Setting Up Ubuntu For Programming

- js-Array-prototype-concat.md
- js-Array-prototype-every.md
- js-Array-prototype-filter.md
- js-Array-prototype-forEach.md
> Test PR   - change titles from "js" to "JavaScript"

- Clojure-Basics.md
- Clojure-Conditionals.md
- Clojure-Let-Bindings.md
- Clojure-Loop-Recur.md
- Clojure-Summary.md
- Clojure.md
Adds 5 articles about Clojure (a functional dialect of Lisp) to the Wiki:
* Clojure-Summary
An article about Clojure, and why someone might want to use it.
* Clojure-Basics
An article about the basics of Clojure: defining variables and functions.
* Clojure-Conditionals
An article about logical operators and if/else in Clojure.
* Clojure-Let-Bindings
An article about using let to define local variables.
* Clojure-Loop-Recur
An article about using recursion (and in particular, the loop/recur syntax).
> Articles: Clojures

- Algorithm-Diff-Two-Arrays.md
Use new [**Challenge Solution Template**](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution)
Also add advanced solution
----
If wanted, I can split it into multiple commits for better history.
----
**Please confirm before merging.**  
I will squash locally and push :+1: 
----
> Pending: add code explanations for intermediate and advanced solutions
Pull Request to my branch WELCOME! :100:
> Convert: Diff Two Arrays Challenge Solution

- Code-of-Conduct.md
> shorten the code of conduct and include spamming and trolling

- C-Sharp.md
Closes #784 
Oh I'm Good! :crown:
> Fix attempt at PR 784

- Clojure-Basics.md
- Clojure-Collections.md
- Clojure-Conditionals.md
- Clojure-Functions.md
- Clojure-Hashmaps.md
- Clojure-Let-Bindings.md
- Clojure-Lists.md
- Clojure-Loop-Recur.md
- Clojure-Vectors.md
I created 3 new articles about the 3 most useful types of collection in Clojure (I haven't done sets yet, because sets bore me; I'll do them later). I also made an article about functions, focusing on arity and anonymity.
Additionally, I removed a forward slash in the Clojure-Basics article that was in the wrong place.
> Articles: Clojure collections & functions

- Select-Issues-for-Contributing-Using-Labels.md
- Wiki-Style-Guide.md
- Wiki.md
> Fix: Speech marks on Wiki articles

- Challenge-Change-Text-with-Click-Events.md
@dwd2010 please review
closes #880
> Fix some typo

- Gitter-Embed-Video.md
- Vagrant-Up.md
- Volunteer-Project-Management.md
- video-demo.md
> Articles Starting with V: Rename filenames, add titles

- FreeCodeCamp-Languages.md
- FreeCodeCamp-Style-Algorithms-Guide.md
- Git-Commit-Message.md
- Gitter-Camperbot-Topic.md
- Pair-Programming-Tips.md
- Pair-Programming-Why.md
- Pair-Programming.md
- Return-Early-Pattern.md
- The-main-advantages-of-Free-Code-Camp.md
- Translating-Free-Code-Camp-into-Your-Native-Language.md
- Translation-Chat-Rooms.md
- Translation-Create-Issues.md
- Translation-Create-PR.md
- Translation-Guide.md
- Translation-Review-Work.md
- Translation-Translate.md
- Twitch.md
- Wiki-Become-A-Mod.md
- Wiki-Central.md
- Wiki-Create-Articles-With-Atom.md
- Wiki-Template-Challenge-Solution.md
- Wiki-Template-JavaScript.md
- topic.md
> Articles Starting with T: Rename filenames, add titles

- Wiki-Template-Challenge-Solution.md
Changes headings for the template so they are camperbot ready.
> Updates headings

- es.lang/Ventajas-y-Desventajas-de-JavaScript.md
Translation of [Advantages-and-Disadvantages-of-Javascript.md](https://github.com/FreeCodeCamp/wiki/blob/master/Advantages-and-Disadvantages-of-Javascript.md)
> Article: Create Ventajas-y-Desventajas-de-JavaScript.md

- FreeCodeCamp-Cost.md
- IIFE.md
- Identify-Basic-Internet-Problems-With-Ping.md
- If-Free-Code-Camp-is-free,-how-does-it-make-money.md
- Install-Django-Flask.md
- Installing-Necessary-CLI-Tools.md
- Installing-WordPress-Locally-on-Mac.md
- Integrated-Development-Environments.md
- Intro-to-Yeoman-Angular-Fullstack-Back-End-Projects.md
- JS-isLoggedInAsync.md
> Articles Starting with I: Rename filenames, add titles

- NPM-Behind-Proxy.md
> Articles Starting with N: Rename filenames, add titles

- Algorithm-Return-Largest-Numbers-in-Arrays.md
- Angular-Dynamic-URLs-Using-routeParams.md
- Angular-Make-Useful-APIs.md
- Get-info-about-the-current-user.md
- Guide-to-Back-End-Projects-Table-of-Contents.md
- JS-Math-Max.md
- JS-Math-Min.md
- JS-Math-Pow.md
- JS-Reduce-Made-Easy.md
- Map.md
- Materialize.md
- More-useful-APIs.md
- Mostaganem.md
> Articles Starting with M: Rename filenames, add titles

- Create-NPM-Module.md
closes https://github.com/FreeCodeCamp/wiki/issues/812
> Article: Create NPM Module [in progress]

- Create-NPM-Module.md
- OpenShift-Deployment-Guide.md
Implement suggestions for #884 and #905
> Implement suggested changes to new articles

- camperbot.md
> Asking for help, makes the bot angry #925

- Brownie-Points.md
> Fix Streak link

- Design-Resources-For-Front-End-Developers.md
Refers https://github.com/FreeCodeCamp/wiki/pull/929
> Improve article about design resources

- es.lang/Puntos-Brownie.md
Brownie-Points.md's translation
> Create Puntos-Brownie.md (es.lang)

- Streaks.md
> Fix BrowniePoints link

- es.lang/Racha.md
> Create Racha.md (es.lang)

- es.lang/FreeCodeCamp-Ventajas.md
FreeCodeCamp-Advantages.md's translation
> Create FreeCodeCamp-Ventajas.md (es.lang)

- FreeCodeCamp.md
> Added changes to FreeCodeCamp.md

- es.lang/Ventajas-Y-Desventajas-De-JavaScript.md
- fr.lang/Challenge-Dire-Bonjour-Aux-Elements-HTML.md
- fr.lang/Challenge-Décommenter-HTML.md
- fr.lang/Challenge-Informer-Avec-l-Element-De-Paragraphe.md
- fr.lang/Challenge-Titre-Avec-Un-Element-H2.md
- fr.lang/FR-Home.md
- kr.lang/KR-Home.md
Changes:
- Rename and give title for es articles
- Rename and give title for kr articles
- Rename and give title for fr articles
> Rename and add titles for Non English Languages

- How-To-Install-Screenhero.md
Many people were confused about the ability to create Screen Hero accounts without an invite, so I've clarified it for them.
> Update Screen Hero instructions

- Help-I've-Found-a-Bug.md
> Temporarily add Found-a-Bug article back

- Help-Rooms.md
Addresses https://github.com/FreeCodeCamp/wiki/pull/932/files#r63580359
> Fix symbols markdown from #932

- es.lang/Algoritmo-Mensaje-Secreto.md
Algorithm-Binary-Agents.md's translation
> Create Algoritmo-Mensaje-Secreto.md (es.lang)

- Ruby-History.md
- Ruby-Numbers-Methods.md
- Ruby-Numbers-Operations.md
- Ruby-Numbers.md
- Ruby-String-Methods.md
- Ruby-String-Operators.md
- Ruby-Strings.md
- Ruby.md
Added to/updated some of the Ruby-Strings articles. Also, added new articles for Ruby-Numbers.
> Add ruby strings/numbers

- Algorithm-Where-Art-Thou.md
> Fix wrong title for where are tho

- Python-From-X-Import-Y.md
- Python-Import-Statements.md
- Python-Using-Pip.md
- Python.md
Adds new a python articles to the python main page and modifies the markdown a bit to add spaces and syntax highlight
> Adds new python articles to the TOC

- LocalGroups-List.md
> Add cities, May 18 2016

- Algorithm-Confirm-The-Ending.md
Comfirm -> Confirm.
Misplaced `
> Two errors in Confirm-The-Ending

- CamperBot.md
Camperbot couldn't help as its intro broke down :cry:
> Fix heading format

- Algorithm-No-Repeats-Please.md
Closes #641. I think I've fixed the formatting issues that mess up Camperbot. But if I've missed something, let me know.
> Fix No Repeats formatting

- Python-Functions.md
While writing my function (Slice), I have entered wrong name.
Apology for the inconvenience caused.
> Sorry a mistake was commited

- LocalGroups-List.md
Whole lot of them, for some reason
> Add cities, May 28 2016

- Help-Rooms.md
Also moved .NET to the language area.
> Add vagrant room

- Official-Free-Code-Camp-Chat-Rooms.md
Added vagrant room to the list of official chatrooms.
> Add vagrant room in the list

- Challenge-Golf-Code.md
Closes FreeCodeCamp/FreeCodeCamp#8975
> Fix misspelling of "gold" to "golf" in Golf Code

- Algorithm-Caesars-Cipher.md
> Updated Algorithm Caesar's Cipher

- Algorithm-Check-For-Palindromes.md
> Updated Algorithm Check for Palindromes

- Algorithm-Binary-Agents.md
> Updated Algorithm Binary Agents

- Algorithm-Boo-Who.md
> Updated Algorithm Boo Who

- Algorithm-Reverse-A-String.md
> Updated Algorithm Reverse A String

- Algorithm-Truncate-A-String.md
Added in an advanced one-line solution that uses nested ternary operators. The solution also utilizes the slice() method - which is what the student is "supposed" to use to solve this Algorithm challenge. The current solution uses the substr() method, so I added that into the hint section as well.
> Update algorithm truncate

- Algorithm-Diff-Two-Arrays.md
> Updated Algorithm Diff Two Arrays

- Algorithm-Convert-HTML-Entities.md
> Updated Algorithm Convert HTML Entities

- Algorithm-Confirm-The-Ending.md
> Updated Algorithm Confirm the Ending

- Algorithm-Drop-It.md
> Updates Algorithm Drop it

- Algorithm-Convert-HTML-Entities.md
Closes FreeCodeCamp/FreeCodeCamp#8957
> Fix convert HTML entities solutions

- FreeCodeCamp-Fork-Windows.md
I updated the wiki pages with the missing .env file, based on the CONTRIBUTING.md.
closes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9085
> Setting up FreeCodeCamp for Windows #9085

- Algorithm-Sum-All-Primes.md
> Update Algorithm Sum All Primes

- Algorithm-Chunky-Monkey.md
> Updated Algorithm Chunky Monkey

- Algorithm-Roman-Numeral-Converter.md
> Updated Roman Numeral Converter

- Algorithm-Sum-All-Numbers-In-A-Range.md
> Updated Sum all numbers in a range

- Algorithm-Validate-US-Telephone-Numbers.md
> Updated Validate US Telephone Numbers

- Algorithm-Title-Case-A-Sentence.md
> Update Algorithm Title Case A Sentence

- Algorithm-Sum-All-Odd-Fibonacci-Numbers.md
> Update Algorithm Sum All Odd Fibonacci Numbers

- Algorithm-Pig-Latin.md
> Update Algorithm Pig Latin

- Algorithm-Validate-US-Telephone-Numbers.md
> Update Validate US Thelephone Numbers

- Algorithm-Search-And-Replace.md
> Update Algorithm Search And Replace

- Building-A-Simple-Slider.md
closes #768 
And yes, this took a while :stuck_out_tongue_closed_eyes:
> Article: Sliding Images Easy

- Challenge-Record-Collection.md
> Updates PR 1108

- Algorithm-Friendly-Date-Ranges.md
> Update Algorithm Friendly Date Ranges

- Algorithm-Where-Art-Thou.md
> Updated Algorithm Where Art Thou

- Algorithm-Pairwise.md
> Update Algorithm Pairwise

- Algorithm-Inventory-Update.md
> Update Algorithm Inventory Update

- Challenge-Shopping-List.md
- Update the challenge **Shopping List** to match template.
> Update Challenge Shopping List

- Translation-Chat-Rooms.md
Update Spanish Room Link.
Refer Conversation:
https://gitter.im/AlexTrapp/FreeCodeCampEspa%C3%B1ol?at=57318342b51b0e294850b285
> Update Spanish Room Link.

- Challenge-Convert-Celsius-To-Fahrenheit.md
Update challenge **Convert Celsius to Fahrenheit** according to template.
> Update Challenge Convert Celsius to Fahrenheit

- Challenge-Word-Blanks.md
Update challenge **Word Blanks** according to template.
> Update Challenge Word Blanks

- Challenge-Counting-Cards.md
- Update challenge **Counting Cards** according to the template.
> Update Challenge Counting Cards

- FreeCodeCamp-Issue-Mods.md
- Change `easy` label to `first-timers-only`
- Add note on accepting your own PRs
> Update Issue Mod documentation

- Challenge-Record-Collection.md
Minor corrections made in challenge **Record Collection**.
> Update Challenge Record Collection

- Challenge-Stand-In-Line.md
- Update challenge **Stand In Line** according to template.
> Update Challenge Stand In Line

- README.md
> Adds deprecated notice
