FreeCodeCamp/wiki

js-arguments.md
Fixes the word Argument in text link, where it points to more
information about optimization issues and managing arguments.
=> Fixes the word Argument in link

List-of-Free-Code-Camp-city-based-Campsites.md
The url link for Argentina - Parana link is the same as Brazil -
Apucarana url link.
"Argentina - Parana" group does not exist , so the correct url is the Brazil - Apucarana.
=> Deleted Argentina - Parana url link

List-of-Free-Code-Camp-city-based-Campsites.md
Santa Rosa link belongs to California - United States, not to Argentina.
This PR resolve conflicts in PR #139.
=> Updated Santa Rosa country

List-of-Free-Code-Camp-city-based-Campsites.md
Related to #164
Also aligned Santa Rosa with other California campsite bullet points.
=> Moved Santa Barbara Campsite from Honduras to California

How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp.md
Fixed spelling of 'Congradulations' to 'Congratulations'
=> Fix typo Congradulations

List-of-Free-Code-Camp-city-based-Campsites.md
I removed Islamabad from Afghanistan as it is not in Afghanistan.
It was already present under Pakistan.
=> Islamanad removed from Afghanistan

How-Long-Free-Code-Camp-Takes.md
Updated how long Free Code Camp takes to reflect latest curriculum changes.
*Changed 1,600 hours to 2,080 hours.
*Recalculated weeks to complete based on new hours.
=> updated curriculum completion time

Waypoint-Return-A-Value-From-A-Function-With-Return.md, Waypoint-Use-Conditional-Logic-with-If-Else-Statements.md
While doing the challenges in order, I didn’t encounter the “stop
execution and exit” property of return statements described anywhere.
So, while doing this
[challenge](http://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements) I figured that a camper might be confused as to
why the second statement won’t be executed if the condition is true.
Hence, I decided to add that part in the wiki in case someone looks for
it.
=> Enhanced description about "return" statements in JS

Bonfire-Drop-it.md
The previous version fails the test case: `drop([1, 2, 3, 4], function(n) {return n > 5;}) should return [].` Because `arr.findIndex(func) >= 0 && arr.findIndex(func)` returns `false` in this case rather than a value. With `arr.findIndex(func) >= 0 ? arr.findIndex(func): arr.length`, the length of the array is returned thus `arr.slice()` returns an empty array.
=> Code Solution 2 corrected.

How-to-create-a-Campsite-for-your-city.md
Quite a few campsites have been created either with a `free.code.camp.your.city.san.francisco` sort of URL or with a `Official FCC testland`description. 
This is a second attempt at improving the instructions so that won't happen anymore.
=> Wording changes to improve campsite creation parameters

up_and_running_with_sass.md
Screenshots were not displaying due to an old filepath.
=> Fix filepath for image links.

code-formatting.md
People are too lazy to read the whole thing. They just want to paste their code in pretty format ASAP.
- Moved the multi-line formatting method to top so that people don't accidentally use the single line formatting.
- Modified the heading so that it better shows the intended behavior.
=> Better header for Code Formatting

python-functions.md
Converting python tutorial docs from https://github.com/alayek/python3notes from ipynb to markdown, by preserving formatting. Continuing work from [this PR](https://github.com/alayek/python3notes/pull/1)
=> Add python functions documentation

Python-More-Builtin-Types.md
Converting python tutorial docs from https://github.com/alayek/python3notes from ipynb to markdown, by preserving formatting. Continuing work from [this PR](https://github.com/alayek/python3notes/pull/1)
=> Add python More Builtin types documentation

Python-Operators.md
Converting python tutorial docs from https://github.com/alayek/python3notes from ipynb to markdown, by preserving formatting. Continuing work from [this PR](https://github.com/alayek/python3notes/pull/1)
=> Add python Operators documentation

Get-Screen-Size-In-Pixels.md
A wiki article for getting screen sizes in pixels using the properties available by default in JavaScript and information about each property.
Rename file.
Closes #469
=> Create wiki article for getting screen size

Python-Resources.md
As per discussion with @alayek, we found that most of the newcomers in Python Gitter channel are requesting resources and challenges to practice Python until the FCC challenges are up. Therefore I have curated a list of un-opinionated Python tutorials and Challenges for the newbies to try out.
Requesting @QuincyLarson to review. Since these links are external so please review them as to which ones should be added or which one shouldn't be. If needed I am happy to add more links.
Tagging @Rafase282
=> Add Python Resources Page

Setting-Up-A-React-ES6-Webpack-Project.md
Fixes issues in webpack config example
Fix grammar, implement build folder, update references and trees
Make reference to gitignore boilerplate site not file
Fix help bullet points
Add a quick instructions summary section
Fix entry point using path.join
Appropriately label js code block
=> Fixes issues in webpack config example

Algorithm-Drop-It.md
Renamed the filename to our convention and added the missing `{` that was removed n solution 3.
From #519 #518 #513
=> Renamed Algorithm Drop It filename and fixed Solution 3

Django-Start-Project.md
I tested the pull request by Jake which created this [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Django-Start-Project) article. 
All instructions work fine on my Linux box; but I noticed a few text that could have been better.
@Munsterberg @koustuvsinha @Rafase282 please review the changes.
=> Fix some typos in Django Start Project wiki

Java-Basics.md
Java Core concepts - initial commit.
=> Added Java-Basics file.

Swashbuckle-Swagger-Operation-Alphabetical-Order.md
Swashbuckle normally lists operations on it's Swagger documentation page in the order that the operations appear on the controller. This filter allows for the operations to be listed alphabetically.
Update swashbuckle-swagger-operation-alphabetical-order.md
Update and rename swashbuckle-swagger-operation-alphabetical-order.md to Swashbuckle-Swagger-Operation-Alphabetical-Order.md
Closes #508
=> Arrange operations alphabetically in Swashbuckle Swagger.

Ignore-Files-Committed-To-Git-Repo.md
Wiki article for issue #367: untrack files previously committed from new .gitignore
Rename Ignore-files-committed-to-git-repo.md to Ignore-Files-Committed-To-Git-Repo.md
Uses proper markdown
Also fixed some typos.
closes #570
=> Article: Untrack files from .gitignore

How-to-create-a-Campsite-for-your-city.md
General rephrasing to try to help campers understand the process a bit better:
- People still make URLs like free.code.camp.your.san.francisco
- Adding me as a group Admin makes it easier to reactivate campsites by getting a new leader rather than creating new ones. It sucks that [these](https://github.com/FreeCodeCamp/wiki/issues/304) will have to be removed for that reason.
- Making the oboarding articles easy to find as soon as you create the campsite is helpful, but knowing where to go find them again is invaluable... therefor, here they are.
=> Text improvements - how to create a campsite

Java-Data-Types.md
Java Data types. See if this is all right. #534
=> Java data types

Volunteer-Project-Management.md
Creates a volunteer project management wiki page.
Adds an initial volunteer project management wiki page that outlines the current process and tools being used.
=> Article: Volunteer Project Management

How-GitHub-Issue-Moderators-AKA-Issue-Mods-Work.md
Closes FreeCodeCamp/FreeCodeCamp#7352.
I've added a table of contents for easier navigation and removed the other link near the bottom that is only accessible by current team members.
=> Update Issue Mods Wiki with TOC and link to team

Official-Free-Code-Camp-Chat-Rooms.md
- Fix trailing white spaces and EOL characters.
- Add <kbd><a href="https://gitter.im/FreeCodeCamp/Git"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Git</b></a></kbd> Room to official list of rooms.
=> Add FCC Git room to official list

Git-Behind-Proxy.md
Added article on how to use git behind proxy server.
A lot of our campers are accessing GitHub in their colleges, or workplace. This would surely serve as a reference for them.
=> Add git behind proxy article

How-FreeCodeCamp-Nonprofit-Projects-work.md
Make sure that the details of the nonprofit process are identical on the wiki and FCC by copying all of the recent text changes from https://www.freecodecamp.com/how-nonprofit-projects-work
=> Synchronise the wiki's nonprofit page with the actual FCC nonprofit page

Brownie-Points.md
Noticed that posting on camper news was still listed as an option for getting brownie points
=> Removed Camper News Option

Java-Inheritance.md
Added Inheritance article as per #534. Please have a look @alayek , @Rafase282, @abhisekp
=> Add Java Inheritance wiki

Java-Interfaces.md
Added article on Java Interfaces as per issue #534 . @alayek @theflametrooper @abhisekp have a look.
=> Add Java Interfaces article

Project-Tribute-Page.md
Issue #539 
created a wiki page for the front end project Build a Tribute Page.
Added in what I consider to be tips that I found useful when I first
started designing simple web pages.
=> Article: Front End Tribute Page

Project-Tribute-Page.md
Changes requested on https://github.com/FreeCodeCamp/wiki/pull/726
=> Adding changes that were missing

Gitter.md
File Gitter.md
Filepath FreeCodeCamp/wiki/Gitter.md
This is my first time contributing to FreeCodeCamp, I've updated the file Gitter.md to include a link to all available Gitter channels/rooms as requested in issue #843 . I moved the last paragraph of the original version below my addition so that it flows well when reading it. 
closes #843
=> Added link to Gitter.im rooms

Wiki-Contribute-Fork.md, Wiki.md
1. Update README to change ``##` to `## Steps to follow` (The blank `##` looks too weird/ugly but it serves to controlw hat's displayed at once on gitter chat.
2. Basically copy most of the content with minimal changes into an article we can point to and expand in the future at will beyond the basic capabilities. Maybe make it more general by not having it point to FCC or wiki.
3. Adds the link to the wiki central.
=> Article: How to keep a synced fork of our wiki

Wiki.md
Fix broken link pointing to the guide on becoming a wiki mod.
=> Wiki Central: Fix broken link

Select-Issues-for-Contributing-Using-Labels.md, Wiki-Style-Guide.md, Wiki.md
Fixed some typos, tidied up syntax and colloquialisms for readers whose first language might not be English, tried to make language and presentation more clear and consistent overall.
This doesn’t address any _officially_ submitted issues that I could find, but I write and proofread a lot of technical documentation in real life, so I figure this is one of the best ways I can contribute. I hope you don’t find it obnoxious! 😽
Sorry if my commits are not squashed. I’m not yet ready to face the horror that is command-line git.
=> improve clarity of wiki articles, including label descriptions

up_and_running_with_sass.md
It's syntactically not semantically. From the official website: http://sass-lang.com/documentation/file.SASS_REFERENCE.html
Thanks :smile:
=> Correct the Sass abbreviation

Setting-Up-Ubuntu-For-Programming.md
The link in the ToC to was to a page that didn't exist. I've edited to point to the correct page. No idea why it is highlighting item 6, which I didn't touch.
=> Fixed link to DevTools page in ToC

Python-Function-ID.md
=> Article: Python Function ID

LocalGroups-List.md
National Harbor is in Ft. Washington, MD, not in Washington state.
=> Move National Harbor from WA to MD

Python-Input.md
=> Article: Python Input() Function

Python-Functions.md
Sorry, accidentally pushed to `upstream`, instead of `origin` :disappointed:
=> Added min() and max()

Algorithm-Check-For-Palindromes.md
I noticed a bug while helping out a camper in our FCC Hyderabad meetup. The RegEx should be `0-9`, not `1-9`. Otherwise, it would exclude 0 as an alphanumeric character.
=> Fix a bug in palindrome challenge

Algorithm-Confirm-The-Ending.md
Wiki had a typo in substring, which should be substr. Solution explanation wasn't clear because it omitted mentioning the comparison and contained unnecessary discussion about why using -1 as substr's parameter is a bad idea.
=> Clarify solution for Confirm the Ending algorithm, remove error discussion
